#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/hisense/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=e910

mkdir -p ../../../vendor/hisense/$DEVICE/proprietary
adb pull /system/etc/AudioFilter.csv ../../../vendor/hisense/$DEVICE/proprietary/AudioFilter.csv
adb pull /system/lib/egl/libEGL_adreno200.so ../../../vendor/hisense/$DEVICE/proprietary/libEGL_adreno200.so
adb pull /system/lib/egl/libGLESv1_CM_adreno200.so ../../../vendor/hisense/$DEVICE/proprietary/libGLESv1_CM_adreno200.so
adb pull /system/lib/egl/libGLESv2_adreno200.so ../../../vendor/hisense/$DEVICE/proprietary/libGLESv2_adreno200.so
adb pull /system/lib/hw/copybit.msm7k.so ../../../vendor/hisense/$DEVICE/proprietary/copybit.msm7k.so
adb pull /system/lib/libgsl.so ../../../vendor/hisense/$DEVICE/proprietary/libgsl.so
adb pull /system/lib/libril-qc-1.so ../../../vendor/hisense/$DEVICE/proprietary/libril-qc-1.so
adb pull /system/lib/liboncrpc.so ../../../vendor/hisense/$DEVICE/proprietary/liboncrpc.so
adb pull /system/lib/libdsm.so ../../../vendor/hisense/$DEVICE/proprietary/libdsm.so
adb pull /system/lib/libqueue.so ../../../vendor/hisense/$DEVICE/proprietary/libqueue.so
adb pull /system/lib/libcm.so ../../../vendor/hisense/$DEVICE/proprietary/libcm.so
adb pull /system/lib/libdiag.so ../../../vendor/hisense/$DEVICE/proprietary/libdiag.so
adb pull /system/lib/libmmgsdilib.so ../../../vendor/hisense/$DEVICE/proprietary/libmmgsdilib.so
adb pull /system/lib/libgsdi_exp.so ../../../vendor/hisense/$DEVICE/proprietary/libgsdi_exp.so
adb pull /system/lib/libgstk_exp.so ../../../vendor/hisense/$DEVICE/proprietary/libgstk_exp.so
adb pull /system/lib/libwms.so ../../../vendor/hisense/$DEVICE/proprietary/libwms.so
adb pull /system/lib/libnv.so ../../../vendor/hisense/$DEVICE/proprietary/libnv.so
adb pull /system/lib/libwmsts.so ../../../vendor/hisense/$DEVICE/proprietary/libwmsts.so
adb pull /system/lib/libpbmlib.so ../../../vendor/hisense/$DEVICE/proprietary/libpbmlib.so
adb pull /system/lib/libril-qcril-hook-oem.so ../../../vendor/hisense/$DEVICE/proprietary/libril-qcril-hook-oem.so
adb pull /system/lib/libdss.so ../../../vendor/hisense/$DEVICE/proprietary/libdss.so
adb pull /system/lib/libqmi.so ../../../vendor/hisense/$DEVICE/proprietary/libqmi.so
adb pull /system/lib/liboem_rapi.so ../../../vendor/hisense/$DEVICE/proprietary/liboem_rapi.so
adb pull /system/bin/qmuxd ../../../vendor/hisense/$DEVICE/proprietary/qmuxd
adb pull /system/lib/libmmjpeg.so ../../../vendor/hisense/$DEVICE/proprietary/libmmjpeg.so
adb pull /system/lib/libmmipl.so ../../../vendor/hisense/$DEVICE/proprietary/libmmipl.so
adb pull /system/lib/libmm-adspsvc.so ../../../vendor/hisense/$DEVICE/proprietary/libmm-adspsvc.so
adb pull /system/lib/libOmxH264Dec.so ../../../vendor/hisense/$DEVICE/proprietary/libOmxH264Dec.so
adb pull /system/lib/libOmxMpeg4Dec.so ../../../vendor/hisense/$DEVICE/proprietary/libOmxMpeg4Dec.so
adb pull /system/lib/libOmxVidEnc.so ../../../vendor/hisense/$DEVICE/proprietary/libOmxVidEnc.so
adb pull /system/lib/libOmxWmvDec.so ../../../vendor/hisense/$DEVICE/proprietary/libOmxWmvDec.so
adb pull /system/etc/init.qcom.bt.sh ../../../vendor/hisense/$DEVICE/proprietary/init.qcom.bt.sh
adb pull /system/bin/hci_qcomm_init ../../../vendor/hisense/$DEVICE/proprietary/hci_qcomm_init
adb pull /system/lib/hw/sensors.default.so ../../../vendor/hisense/$DEVICE/proprietary/sensors.default.so


(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/hisense/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/hisense/__DEVICE__/extract-files.sh - DO NOT EDIT

# All the blobs necessary for e910
PRODUCT_COPY_FILES += \\
    vendor/hisense/__DEVICE__/proprietary/AudioFilter.csv:system/etc/AudioFilter.csv \\
    vendor/hisense/__DEVICE__/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \\
    vendor/hisense/__DEVICE__/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \\
    vendor/hisense/__DEVICE__/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \\
    vendor/hisense/__DEVICE__/proprietary/copybit.msm7k.so:/system/lib/hw/copybit.msm7k.so \\
    vendor/hisense/__DEVICE__/proprietary/libgsl.so:system/lib/libgsl.so \\
    vendor/hisense/__DEVICE__/proprietary/libril-qc-1.so:/system/lib/libril-qc-1.so \\
    vendor/hisense/__DEVICE__/proprietary/liboncrpc.so:/system/lib/liboncrpc.so \\
    vendor/hisense/__DEVICE__/proprietary/libdsm.so:/system/lib/libdsm.so \\
    vendor/hisense/__DEVICE__/proprietary/libqueue.so:/system/lib/libqueue.so \\
    vendor/hisense/__DEVICE__/proprietary/libcm.so:/system/lib/libcm.so \\
    vendor/hisense/__DEVICE__/proprietary/libdiag.so:/system/lib/libdiag.so \\
    vendor/hisense/__DEVICE__/proprietary/libmmgsdilib.so:/system/lib/libmmgsdilib.so \\
    vendor/hisense/__DEVICE__/proprietary/libgsdi_exp.so:/system/lib/libgsdi_exp.so \\
    vendor/hisense/__DEVICE__/proprietary/libgstk_exp.so:/system/lib/libgstk_exp.so \\
    vendor/hisense/__DEVICE__/proprietary/libwms.so:/system/lib/libwms.so \\
    vendor/hisense/__DEVICE__/proprietary/libnv.so:/system/lib/libnv.so \\
    vendor/hisense/__DEVICE__/proprietary/libwmsts.so:/system/lib/libwmsts.so \\
    vendor/hisense/__DEVICE__/proprietary/libpbmlib.so:/system/lib/libpbmlib.so \\
    vendor/hisense/__DEVICE__/proprietary/libril-qcril-hook-oem.so:/system/lib/libril-qcril-hook-oem.so \\
    vendor/hisense/__DEVICE__/proprietary/libdss.so:/system/lib/libdss.so \\
    vendor/hisense/__DEVICE__/proprietary/libqmi.so:/system/lib/libqmi.so \\
    vendor/hisense/__DEVICE__/proprietary/liboem_rapi.so:system/lib/liboem_rapi.so \\
    vendor/hisense/__DEVICE__/proprietary/qmuxd:system/bin/qmuxd \\
    vendor/hisense/__DEVICE__/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \\
    vendor/hisense/__DEVICE__/proprietary/libmmipl.so:system/lib/libmmipl.so \\
    vendor/hisense/__DEVICE__/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \\
    vendor/hisense/__DEVICE__/proprietary/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \\
    vendor/hisense/__DEVICE__/proprietary/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \\
    vendor/hisense/__DEVICE__/proprietary/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \\
    vendor/hisense/__DEVICE__/proprietary/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \\
    vendor/hisense/__DEVICE__/proprietary/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \\
    vendor/hisense/__DEVICE__/proprietary/hci_qcomm_init:system/bin/hci_qcomm_init \\
    vendor/hisense/__DEVICE__/proprietary/sensors.default.so:system/lib/hw/sensors.default.so
EOF

./setup-makefiles.sh
